config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :articles
  resources :users, except: [:new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum: 3, maximum: 30}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: {minimum: 3, maximum: 25}, uniqueness: {case_sensitive: false}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitive: false},
                    format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end
  def new
    @article = Article.new
  end
  def edit
  end
  def create
    @article = Article.new(article_params)
    #debugger
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article is successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  def show
  end
  def destroy
    @article.destroy
    flash[:notice] = "Article was successfully deleted"
    redirect_to articles_path
  end
  def update
    if @article.update(article_params)
      flash[:notice] = "Article is successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title,:description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home

    end

    def about

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
  end
  
  def create
    #debugger
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User is sign up successful"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit 
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account is updated successfully"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back to listing articles', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit existing article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing all articles</h1>
<%= link_to 'Create new Article', new_article_path %>
<br /><br />
<table>
<tr>
  <td><strong>Title<?strong></td>
  <td><strong>Description</strong></td>
</tr>
<% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Delete', article_path(article), method: :delete, data: {confirm: "Are you Sure?"} %></td>
    <td><small>created by <%=article.user.username if article.user %>
      <%= time_ago_in_words(article.created_at) %> ago 
      updated_at: <%= time_ago_in_words(article.updated_at) %> ago </small>
    </td>  
<% end %>
</table>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Showing selected article</h1>
<p>
  Title: <%= @article.title %>
</p>
<p>
  Description: <%= @article.description %>
</p>

<%= link_to 'Edit this Article', edit_article_path(@article) %> |
<%= link_to 'Back to listing articles', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
<ul>
    <li><%= msg %></li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubyrails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<!Doctype html>
<html>
<head>
    <title>HomePage</title>
</head>
<body>
    <h1>This is about page</h1>
    <%= link_to 'Home', root_path %>
    <br /><br />
    <div>
        <%= image_tag("Rails.png", width: 'auto', height: 'auto') %>
    </div>
</body>
</html>

app/views/pages/home.html.erb
<!Doctype html>
<html>
<head>
    <title>HomePage</title>
</head>
<body>
    <h1>Welcome User</h1>
    <%= link_to 'Alpha Blog RubyRails', articles_path %> | 
    <%= link_to 'About', about_path %>
    <br /><br />
    <div>
        <%= image_tag("Rails.png", width: 'auto', height: 'auto') %>
    </div>
</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <p><%= pluralize(obj.errors.count,"error") %> prevented the article from being created</p>
	<ul>
		<% obj.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.submit (@user.new_record? ? "Sign Up" : "Update your account") %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Signup for Alpha Blog</h1>

<%= render 'form' %>